language: java
before_install:
- openssl aes-256-cbc -K $encrypted_81ae95a4601b_key -iv $encrypted_81ae95a4601b_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/target mwi@193.196.7.215:/home/mwi/test
  on:
    branch: master
addons:
  ssh_known_hosts:
  - 193.196.7.215