version: '3.1'
services:
  mwi:
    image: mwi:latest
    ports:
      - '8082:8080'
    environment:
      MWI_URL: 'http://10.3.15.45:8082'
      MWI_DB_URL: 'jdbc:mysql://10.3.15.45:3306/mwi?autoReconnect=true&user=mwi&password=mwi2014&serverTimezone=UTC'